version: "3.3"

services:
  geoserver:
    image: kartoza/geoserver:2.18.0
    environment:
      - SAMPLE_DATA=true
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - ${GEOSERVER_PORT}:8080

  geoserver-setup:
    build:
      context: ../../Docker/GeoserverSetup/geoserver-setup-context
      args:
        GEOSERVER_DATA_GITHUB_REPOSITORY: ${GEOSERVER_DATA_GITHUB_REPOSITORY}
        GEOSERVER_DATA_GITHUB_REPOSITORY_NAME: ${GEOSERVER_DATA_GITHUB_REPOSITORY_NAME}
        GEOSERVER_DATA_IMPORT_DIR: ${GEOSERVER_DATA_IMPORT_DIR}
    environment:
      - WORKSPACE=${GEOSERVER_WORKSPACE}
      - MAX_CONNECTION_ATTEMPTS=${GEOSERVER_MAX_CONNECTION_ATTEMPTS}
      - TIME_CONNECTION_ATTEMPTS=${GEOSERVER_TIME_CONNECTION_ATTEMPTS}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_CATALOG_ADDRESS=${GEOSERVER_CATALOG_ADDRESS}
      - GEOSERVER_SOCKET_HOST=${GEOSERVER_SOCKET_HOST}
      - GEOSERVER_SOCKET_PORT=${GEOSERVER_SOCKET_PORT}
